# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TLYNb4JY74LQ3PEz9Ja502LgVIV9T_J6
"""

import random

def jaccard_similarity(file1, file2):
  # split texts into sets of words
  set1= set(file1.split())
  set2= set(file2.split())

  #find intersection and union
  intersection = set1.intersection(set2)
  union = set1.union(set2)

  #calculate jaccard similarity
  similarity = len(intersection) / len(union)

  #return similarity and intersection words
  return similarity, intersection

#input texts
file1 = "History is the systematic study of the past."
file2 = "History is the systematic study of the past this is just for practice."

#calculate similarity and  get common words
similarity, common_words = jaccard_similarity(file1, file2)

#print results
print(f"similarity: {similarity:.2f}")
print(f"common words: {common_words}")